language: android
android:
  update-sdk: true
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - bash ./android-wait-for-emulator.sh
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedCheck
